change

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,8 +7,8 @@ branding:
 
 inputs:
   upstream:
-    description: The full HTTPS upstream URL.
-    required: true
+    description: <user>/<repo>
+    required: false
   branch:
     description: The upstream branch that is rebased on.
     required: false
@@ -28,7 +28,14 @@ runs:
     - run: |
         set -ex;
 
-        git remote add upstream ${{ inputs.upstream }};
+        $UPSTREAM=${{ inputs.upstream }};
+        if [ -z "$UPSTREAM" ]; then
+            echo ${{ inputs.token }} | gh auth login --with-token;
+            $UPSTREAM=$(a.json | jq .parent.full_name);
+            if [ -z "$UPSTREAM" ]; then echo "can't find upstream" && exit 1;
+        fi;
+
+        git remote add upstream https://github.com/$UPSTREAM.git;
 
         git fetch upstream ${{ inputs.branch }} --depth=${{ inputs.depth }};
 
@@ -36,11 +43,6 @@ runs:
         git config --local user.name "GitHub Action";
 
         git rebase upstream/${{ inputs.branch }};
+
+        git push origin $(git branch --show-current) --force-with-lease
       shell: bash
-    - id: set-output
-      shell: bash
-      run: |
-        if [ "$(git status | grep diverged)" ]; then
-          echo push is needed.
-          echo ::set-output name=needs-push::1
-        fi;
