fix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,17 +10,13 @@ inputs:
     description: <user>/<repo>
     required: false
   branch:
-    description: The upstream branch that is rebased on.
+    description: The upstream branch that is rebased on
     required: false
     default: master
   depth:
     description: The fetch depth
     required: false
     default: 100
-outputs:
-  needs-push:
-    description: Whether push is needed.
-    value: ${{ steps.set-output.outputs.needs-push }}
 
 runs:
   using: composite
@@ -29,10 +25,10 @@ runs:
         set -ex;
 
         $UPSTREAM=${{ inputs.upstream }};
-        if [ -z "$UPSTREAM" ]; then
+        if [ -z $UPSTREAM ]; then
             echo ${{ inputs.token }} | gh auth login --with-token;
             $UPSTREAM=$(a.json | jq .parent.full_name);
-            if [ -z "$UPSTREAM" ]; then echo "can't find upstream" && exit 1;
+            if [ -z $UPSTREAM ]; then echo "Can't find upstream" && exit 1;
         fi;
 
         git remote add upstream https://github.com/$UPSTREAM.git;
@@ -40,9 +36,11 @@ runs:
         git fetch upstream ${{ inputs.branch }} --depth=${{ inputs.depth }};
 
         git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com";
-        git config --local user.name "GitHub Action";
+        git config --local user.name  "GitHub Actions";
 
         git rebase upstream/${{ inputs.branch }};
 
-        git push origin $(git branch --show-current) --force-with-lease
+        if [ "$(git status | grep diverged)" ]; then
+          git push origin $(git branch --show-current) --force-with-lease;
+        fi;
       shell: bash
